services:
  nginx:
    image: nginx:alpine
    container_name: api-nginx
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-1
      - api-2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "48MB"
  api-1: &api
    build: .
    container_name: payments-api-1
    restart: unless-stopped
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://gateway-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://gateway-fallback:8080
      - MAX_PARALLELISM=6
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=payments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - redis
      - postgres
    volumes:
      - redis-socket:/var/run/redis
    networks:
      - backend
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "108MB"

  api-2:
    <<: *api
    container_name: payments-api-2

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: [
        "sh",
        "-c",
        "mkdir -p /var/run/redis && \
        redis-server \
        --save '' \
        --appendonly no \
        --maxclients 5000 \
        --unixsocket /var/run/redis/redis.sock \
        --unixsocketperm 777 \
        --port 0 \
        --protected-mode no \
        --hz 10",
      ]
    networks:
      - backend
    volumes:
      - redis-socket:/var/run/redis
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "86MB"

  postgres:
    image: postgres:17.6-alpine3.22
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "128MB"

networks:
  backend:
    driver: bridge

volumes:
  redis-socket:
  postgres-data:
